### ISSUE TITLE
Does not compile on debian stretch

### ISSUE THREAD

**Issue by hotbso** [jtanx/libclipboard#10]
Error is:
/usr/bin/cc   -I/home/holger/git/libclipboard/include  -std=c99 -Wall -pedantic -g -fdiagnostics-color=auto   -o CMakeFiles/clipboard.dir/src/clipboard_x11.c.o   -c /home/holger/git/libclipboard/src/clipboard_x11.c
/home/holger/git/libclipboard/src/clipboard_x11.c: In function 'clipboard_text_ex':
/home/holger/git/libclipboard/src/clipboard_x11.c:607:29: error: storage size of 'timeout' isn't known
             struct timespec timeout;

As a hack I added 
#define __need_timespec
to clipboard_x11.c

I guess a proper solution is to compile it according to some POSIX standard.

**Comment by jtanx** [comment]
Thanks for the report! It should be fixed now.
