### ISSUE TITLE
cmake -DLIBCLIPBOARD_ADD_SOVERSION=ON adds a literal ".VERSION" rather than ".1" to the .so

### ISSUE THREAD

**Issue by lockywolf** [jtanx/libclipboard#15]
Hello.

I am building libclibpboard 1.0 like this:

```
CFLAGS="$SLKCFLAGS" \
cmake -DLIBCLIPBOARD_ADD_SOVERSION=ON \
      -DBUILD_SHARED_LIBS=ON \
      -DLIBCLIPBOARD_USE_STDCALL=on \
      -DCMAKE_C_FLAGS="$SLKCFLAGS" \
      -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
      -DCMAKE_BUILD_TYPE="Release" \
      -DCMAKE_INSTALL_PREFIX=/usr \
      .
make
```

which produces a file named `usr/lib/libclipboard.so.VERSION`.

Seems incorrect.

**Comment by jtanx** [comment]
What's your cmake version and OS? Seems odd that you're enabling stdcall unless this is for cygwin or something?

**Comment by lockywolf** [comment]
Well, I have no idea what it is, and this is not documented, so I just decided that it's better to have it than not have.

**Comment by jtanx** [comment]
It works for me, so again, what's your OS and cmake version? Also what's the output of 

```
grep LIBCLIPBOARD_VERSION CMakeCache.txt
```

**Comment by lockywolf** [comment]
Sorry, just edited.

This is Slackware-current, kernel and glibc are as above.

**Comment by jtanx** [comment]
Ah right, are you working off the tarball? This is in a commit that comes after 227588ff3a5ed02a15a3c56915efd5a48c751362

I can probably tag again though.

**Comment by jtanx** [comment]
I've pushed v1.1, try that.

**Comment by ghost** [comment]
Works, thank you.
